site_name: SCC Utility
docs_dir: .
site_dir: ../site
repo_url: https://github.com/Netteam-Globalconnect/scc_utility

theme:
  name: material
  palette:
    scheme: slate

plugins:
  - gen-files:
      scripts:
        - gen_services.py
  - awesome-pages:
  - mkdocstrings:
      handlers:
        python:
          paths: ["../src"]
          options:
            docstring_style: google
            show_signature: true
            separate_signature: true
            show_source: true
            members_order: source
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - mkdocs_click

